#!/usr/bin/env sh

rm -rf dist

"$(dirname "$0")"/parcel build \
  --public-url "./" \
  --no-source-maps \
  --no-autoinstall \
  --no-content-hash || exit 1

if [ -f dist/index.html ]; then
  npx prettier dist/index.html --write
fi
